let menuItemsData = 
    [{id: "1",
    name: "Бургер Классика",
    price: "359",
    img: "img/menu/classic.png",
    category: "burger"},
    {id: "2",
    name: "Бургер BBQ",
    price: "329",
    img: "img/menu/bbq.png",
    category: "burger"},
    {id: "3",
    name: "Бургер Итальянский",
    price: "389",
    img: "img/menu/italian.png",
    category: "burger"},
    {id: "4",
    name: "Бургер Грибной",
    price: "389",
    img: "img/menu/mushroom.png",
    category: "burger"},
    {id: "5",
    name: "Пицца Пепперони",
    price: "599",
    img: "img/menu/pizza pepperoni.png",
    category: "pizza"},
    {id: "6",
    name: "Пицца BBQ",
    price: "599",
    img: "img/menu/pizza bbq.png",
    category: "pizza"},
    {id: "7",
    name: "Пицца Маргарита",
    price: "399",
    img: "img/menu/pizza margarita.png",
    category: "pizza"},
    {id: "8",
    name: "Пицца 4 сыра",
    price: "499",
    img: "img/menu/pizza cheese.png",
    category: "pizza"},
    {id: "9",
    name: "Чай Rich с манго",
    price: "99",
    img: "img/menu/tea rich mango.png",
    category: "drinks"},
    {id: "10",
    name: "Добрый Cola",
    price: "99",
    img: "img/menu/cola.png",
    category: "drinks"},
    {id: "11",
    name: "Чай Rich с лимоном",
    price: "99",
    img: "img/menu/tea rich lemon.png",
    category: "drinks"},
    {id: "12",
    name: "Добрый апельсин",
    price: "99",
    img: "img/menu/orange.png",
    category: "drinks"},
    {id: "13",
    name: "Куриные ножки",
    price: "249",
    img: "img/menu/fried legs.png",
    category: "chicken"},
    {id: "14",
    name: "Куриные крылышки",
    price: "249",
    img: "img/menu/fried wings.png",
    category: "chicken"},
    {id: "15",
    name: "Куриные стрипсы",
    price: "249",
    img: "img/menu/strips.png",
    category: "chicken"},
    {id: "16",
    name: "Куриные наггетсы",
    price: "249",
    img: "img/menu/nuggets.png",
    category: "chicken"},
    {id: "17",
    name: "Креветки",
    price: "249",
    img: "img/menu/shrimps.png",
    category: "fish"},
]